import React from 'react'
import type { Metadata } from 'next'
import About from '@/components/about/about'

export const metadata: Metadata = {
  title: 'JS DHAMI | About',
  description: 'Generated by create next app',
}

const about = () => {
  return (
    <>
      
    <div className='w-full h-screen justify-around text-center justify-items-center '>
    <About/>
    </div>
    
    </>
  )
}

export default about