import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css';
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
const inter = Inter({ subsets: ['latin'] })
import { Theme } from '@radix-ui/themes';
import Header from '@/components/header/header';

export const metadata: Metadata = {
  title: 'JS DHAMI | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}

) {
  return (
    <html lang="en" >
       
        <body className={inter.className}>
        <Theme> 
        {/* <Navbar/> */}
        <Header />
        {children}
        <Footer/>
        </Theme>
        </body>
       
    </html>
  )
}
